### ISSUE TITLE
example with async await

### ISSUE THREAD

**Issue by webmobiles** [mrm8488/from-callbacks-to-util.promisify#1]
In your code; it's possible to add an example with async /await ? thanks

```
const util = require('util');

const writeFile = util.promisify(fs.writeFile);

writeFile('/tmp/test3.js',"console.log('Hello world with promisify!');")

.then(() => console.log('file created successfully with promisify!'))

.catch(error => console.log(error));
```

**Comment by mrm8488** [comment]
async function writeFileFunction() {
try {
await writeFile(...)
}catch (error) { console.error(error)}

**Comment by mrm8488** [comment]
Smth like that?

**Comment by webmobiles** [comment]
yes ; looks it's working, here my implementation:

```
async function aWriteFile ( target, content) {
  const writeFile = util.promisify(require("fs").writeFile);
    return writeFile(target, content).then(function () {
      console.log('done');
    });
}

fSourceFile = './src/generaApp.js';
fTargetFile = './src/App.js';

Twig.renderFile(fSourceFile, templateGlobalValues, (err, txtContent) => {
  aWriteFile (fTargetFile, txtContent);
});

```

**Comment by mrm8488** [comment]
So good Dave. Remember you can do await writeFile (...);
return "it worked";

And the function async function writeFileFunction will continue returning a
Promise. It always return a Promise. Even if the body of the fun is just:
return 45;


El 30 oct. 2017 3:05 p. m., "Dave I." <notifications@github.com> escribió:

yes ; looks it's working, here my implementation:

async function aWriteFile ( target, content) {
  const writeFile = util.promisify(require("fs").writeFile);
    return writeFile(target, content).then(function () {
      console.log('done');
    });
}

fSourceFile = './src/generaApp.js';
fTargetFile = './src/App.js';

Twig.renderFile(fSourceFile, templateGlobalValues, (err, txtContent) => {
  aWriteFile (fTargetFile, txtContent);
});


—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/mrm8488/from-callbacks-to-util.promisify/issues/1#issuecomment-340453826>,
or mute the thread

**Comment by webmobiles** [comment]
thanks, my final version:

```
async function aWriteFile ( target, content) {
  const writeFile = util.promisify(require("fs").writeFile);
  try {
    await writeFile(target, content);
    console.log('done');
  } catch (error) {
    console.error(error)
  }
}
```

**Comment by mrm8488** [comment]
Great you also can do this:

const {promosify} = require("util");
//Object destructor

**Comment by mrm8488** [comment]
I have updated the article:
https://github.com/mrm8488/from-callbacks-to-util.promisify
